#!/bin/bash
printf "The sum of WATER (%s) and STIR (%s) is: %s in base bestchol\n" "$WATER" "$STIR" "$(printf '%d\n' "$((5#$(echo $WATER | tr 'water' '01234') + 5#$(echo $STIR | tr 'stir.' '01234'))) " | tr '012345' 'bestchol')"
