#!/usr/bin/env bash
# Script installs Nginx on a server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        
        error_page 404 /error404.html;
        location = /error404.html {
                root /var/www/html;
                internal;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
