#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend alvoniah.tech
    timeout client  30000
    bind 0:80
    default_backend alvoniah.tech_backend

backend alvoniah.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 328109-web-01 34.207.57.227 check
    server 328109-web-02 52.3.250.125 check
EOT

sudo service haproxy restart
